ALTER TABLE LEARNING.CADRE_RECORD ADD COLUMN REGISTER_NUMBER VARCHAR(12);
ALTER TABLE LEARNING.CADRE_RECORD ADD COLUMN CREATED_AT TIMESTAMP WITH DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE LEARNING.CADRE_RECORD ADD COLUMN DELETED_AT TIMESTAMP WITH DEFAULT NULL;
ALTER TABLE LEARNING.CADRE_RECORD ADD COLUMN DOCUMENT_ORIGINAL_FILENAME VARCHAR(50);
ALTER TABLE LEARNING.CADRE_RECORD ADD COLUMN VIDEO VARCHAR(50);
ALTER TABLE LEARNING.CADRE_RECORD ADD COLUMN VIDEO_ORIGINAL_FILENAME VARCHAR(50);
ALTER TABLE LEARNING.CADRE_RECORD ADD COLUMN EXTERNAL_LINK VARCHAR(300);
ALTER TABLE LEARNING.CADRE_RECORD ADD COLUMN SOURCE INT;
ALTER TABLE LEARNING.CADRE_RECORD ADD COLUMN SUBMITTER VARCHAR(12);
