ALTER TABLE GROUP_COUNSEL_MEMBER DROP PRIMARY KEY;

ALTER TABLE GROUP_COUNSEL_MEMBER
ADD CONSTRAINT GROUP_COUNSEL_MEMBER_PK
PRIMARY KEY (GROUP_COUNSEL_ID, REGISTER_NUMBER);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE GROUP_COUNSEL_MEMBER');