ALTER TABLE DOCUMENT ADD COLUMN TERM_YEAR INT;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.DOCUMENT');

ALTER TABLE DOCUMENT ADD COLUMN TERM_SEMESTER INT;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.DOCUMENT');

ALTER TABLE DOCUMENT ADD COLUMN ORIGINAL_FILENAME VARCHAR(50);
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.DOCUMENT');