ALTER TABLE LEARNING.OTHER_RECORD ADD COLUMN CHECK INT WITH DEFAULT 0;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.OTHER_RECORD');
ALTER TABLE LEARNING.OTHER_RECORD ADD COLUMN STATUS VARCHAR(2) WITH DEFAULT '1';
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.OTHER_RECORD');