ALTER TABLE LEARNING.STUDENT_COURSE_RECORD DROP DOCUMENT;
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD DROP ORIGINAL_FILENAME;

CREATE TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT
(
    ID INT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    CRID INT,
    DOCUMENT VARCHAR(50),
    ORIGINAL_FILENAME VARCHAR(50),
    CONSTRAINT STUDENT_COURSE_RECORD_DOCUMENT_STUDENT_COURSE_RECORD_ID_fk FOREIGN KEY (CRID) REFERENCES STUDENT_COURSE_RECORD(ID)
    CONSTRAINT "STUDENT_COURSE_RECORD_DOCUMENT_ID_pk" UNIQUE (ID);
);

ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT ADD COLUMN DELETED_AT TIMESTAMP WITH DEFAULT NULL ;
