ALTER TABLE STUDYPLAN RENAME COLUMN FILE_PATH TO MAIN_FILE_PATH;
ALTER TABLE STUDYPLAN ADD COLUMN SUB_FILE_PATH VARCHAR(50);
ALTER TABLE STUDYPLAN ADD COLUMN TERM_YEAR INTEGER;
ALTER TABLE STUDYPLAN ADD COLUMN TERM_SEMESTER INTEGER;
ALTER TABLE STUDYPLAN ADD COLUMN MAIN_ORIGINAL_FILENAME VARCHAR(50);
ALTER TABLE STUDYPLAN ADD COLUMN SUB_ORIGINAL_FILENAME VARCHAR(50);
