CREATE OR REPLACE VIEW STUDENT_COURSE_RECORD_SUBMIT_INFO AS (
  SELECT A.TERM_YEAR,
         A.TERM_SEM,
         A.SUBMITTED_AT,
         A.REGISTER_NUMBER,
         COUNT(*) CNT
  FROM STUDENT_COURSE_RECORD A
  WHERE A.STATUS = '5'
    AND SUBMITTED_AT IS NOT NULL
  GROUP BY A.TERM_YEAR, A.TERM_SEM, A.REGISTER_NUMBER, A.SUBMITTED_AT
);

