CREATE OR REPLACE VIEW STU_SELECT_COURSE AS (
    SELECT A.REG_NO,B.* FROM HS014357.VCOURSE_SELECT AS A,COURSE_INFO AS B
    WHERE A.COURSE_NUM = B.COURSE_NUM
);

CREATE OR REPLACE VIEW TEA_TEACHING_COURSE AS (
    SELECT A.STAFF_CODE,B.* FROM HS014357.TEACHING AS A,COURSE_INFO AS B
    WHERE A.SBJ_NUM = B.COURSE_NUM
);

