ALTER TABLE RESUME ADD COLUMN TERM_YEAR INTEGER;
ALTER TABLE RESUME ADD COLUMN TERM_SEMESTER INTEGER;
ALTER TABLE RESUME ADD COLUMN ORIGINAL_FILENAME VARCHAR(50);
ALTER TABLE LIFEPLAN ADD COLUMN TERM_YEAR INTEGER;
ALTER TABLE LIFEPLAN ADD COLUMN TERM_SEMESTER INTEGER;
ALTER TABLE LIFEPLAN ADD COLUMN ORIGINAL_FILENAME VARCHAR(50);
