CREATE TABLE COURSE_RECORD_UNLOCK_STATUS
    (
        ACTIVE_YEAR INTEGER NOT NULL,
        ACTIVE_SEM CHAR(1) NOT NULL,
        REG_NO VARCHAR(20) NOT NULL,
        START_TIME TIMESTAMP NOT NULL,
        END_TIME TIMESTAMP NOT NULL,
        PRIMARY KEY (ACTIVE_YEAR, ACTIVE_SEM, REG_NO),
        CONSTRAINT COURSERECORDUNLOCKSTATUS_ck1 CHECK (START_TIME<END_TIME)
    ); 
    
CREATE TABLE PERFORMANCE_UNLOCK_STATUS
    (
        ACTIVE_YEAR INTEGER NOT NULL,
        REG_NO VARCHAR(20) NOT NULL,
        START_TIME TIMESTAMP NOT NULL,
        END_TIME TIMESTAMP NOT NULL,
        PRIMARY KEY (ACTIVE_YEAR, REG_NO),
        CONSTRAINT PERFORMANCE_UNLOCK_STATUS_ck1 CHECK (START_TIME<END_TIME)
    ); 