CREATE TABLE GROUP_COUNSEL_MEMBER
(
  GROUP_COUNSEL_ID INTEGER     NOT NULL
    CONSTRAINT GROUP_COUNSEL_MEMBER_GROUP_COUNSEL_ID_FK
      REFERENCES GROUP_COUNSEL
      ON DELETE CASCADE,
  REGISTER_NUMBER  VARCHAR(12) NOT NULL
    CONSTRAINT GROUP_COUNSEL_MEMBER_PK
      PRIMARY KEY
);