CREATE TABLE GROUP_COUNSEL
(
  ID                INTEGER GENERATED ALWAYS AS IDENTITY
    CONSTRAINT GROUP_COUNSEL_PK
      PRIMARY KEY,
  START_TIME        TIMESTAMP(6),
  END_TIME          TIMESTAMP(6),
  TITLE             VARCHAR(50),
  ORIGINAL_FILENAME VARCHAR(100),
  RANDOM_FILENAME   VARCHAR(100),
  LOCATION          VARCHAR(100),
  DESCRIPTION       VARCHAR(300),
  COUNSELOR         VARCHAR(10) NOT NULL,
  SUBMITTER         VARCHAR(10),
  CREATED_AT        TIMESTAMP(6) DEFAULT CURRENT TIMESTAMP
);