ALTER TABLE AUTOBIOGRAPHY ADD COLUMN TERM_YEAR INT;

ALTER TABLE AUTOBIOGRAPHY ADD COLUMN TERM_SEMESTER INT;

ALTER TABLE AUTOBIOGRAPHY RENAME COLUMN USE TO TOPIC;

ALTER TABLE AUTOBIOGRAPHY RENAME COLUMN FILE_PATH TO MAIN_FILE_PATH;

ALTER TABLE AUTOBIOGRAPHY RENAME COLUMN EXTRA_FILE_PATH TO SUB_FILE_PATH;

ALTER TABLE AUTOBIOGRAPHY ADD COLUMN MAIN_ORIGINAL_FILENAME VARCHAR(50);

ALTER TABLE AUTOBIOGRAPHY ADD COLUMN SUB_ORIGINAL_FILENAME VARCHAR(50);

