ALTER TABLE SYSTEM_CONFIG 
    ADD COLUMN UPLOAD_TYPE char(30) NOT NULL DEFAULT '*'
    ADD COLUMN TERM_YEAR int NOT NULL DEFAULT -1
    ADD COLUMN TERM_SEMESTER int NOT NULL DEFAULT -1
    ADD CONSTRAINT SYSTEM_CONFIG_TYPE_SEM_UNI UNIQUE (TERM_YEAR, TERM_SEMESTER, UPLOAD_TYPE)
;