CREATE OR REPLACE VIEW STU_COURSE_RECORD_WITH_DETAILS AS (
  SELECT A.*,B.CNAME, C.STAFF_CNAME
  FROM STUDENT_COURSE_RECORD AS A
         INNER JOIN HS014357.STU_BASIS AS B ON A.REGISTER_NUMBER = B.REG_NO
         LEFT JOIN HS014357.STAFF C ON A.VERIFIER_STAFF_CODE = C.STAFF_CODE
);

