ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_COPY ADD COLUMN VERIFIED_AT TIMESTAMP WITH DEFAULT NULL ;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.STUDENT_COURSE_RECORD_COPY');
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_COPY ADD COLUMN VERIFY_MESSAGE VARCHAR(400);
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.STUDENT_COURSE_RECORD_COPY');
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_COPY ADD COLUMN VERIFIER_STAFF_CODE VARCHAR(10);
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.STUDENT_COURSE_RECORD_COPY');