ALTER TABLE "AUTOBIOGRAPHY"
    ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
    ADD COLUMN DELETED_AT TIMESTAMP DEFAULT NULL;

ALTER TABLE "DOCUMENT" 
    ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
    ADD COLUMN DELETED_AT TIMESTAMP DEFAULT NULL;

ALTER TABLE "LIFEPLAN" 
    ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
    ADD COLUMN DELETED_AT TIMESTAMP DEFAULT NULL;

ALTER TABLE "RESUME" 
    ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
    ADD COLUMN DELETED_AT TIMESTAMP DEFAULT NULL;

ALTER TABLE "STUDYPLAN" 
    ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
    ADD COLUMN DELETED_AT TIMESTAMP DEFAULT NULL;

