CREATE OR REPLACE VIEW STU_ABSENCE AS (
 SELECT
        A.*,
        B.AR_CNAME,
        C.SPERIOD,
        C.SPRD_NAME
 FROM HS014357.STU_ABSENCE AS A,
      HS014357.STU_AR_DATA AS B,
      HS014357.SPERIOD_MARK AS C
 WHERE A.AR_CODE = B.AR_CODE
   AND A.PERIOD = C.SPERIOD
);

CREATE VIEW STU_AR_LEAVE_ONLY AS (
    SELECT * FROM HS014357.STU_AR_DATA WHERE AR_TYPE IS NULL
);
