CREATE VIEW COURSE_INFO
AS
SELECT TERM_SEM,TERM_YEAR,CLASS_CNAME,COURSE_NUM,COURSE_CNAME,listagg(STAFF_CNAME,',') within group (ORDER BY STAFF_CNAME) as names
  FROM (SELECT C.TERM_SEM,C.TERM_YEAR,C.CLASS_CNAME,C.COURSE_CNAME,C.COURSE_NUM,D.STAFF_CNAME
        FROM (SELECT A.COURSE_CNAME,A.TERM_YEAR,A.TERM_SEM,A.CLASS_CNAME,A.COURSE_NUM,B.STAFF_CODE
              FROM  HS014357.VCOURSE AS A
                LEFT JOIN HS014357.TEACHING AS B
                  ON A.COURSE_NUM = B.SBJ_NUM) AS C,
          (SELECT STAFF_CODE,STAFF_CNAME FROM HS014357.STAFF ORDER BY STAFF_CODE) AS D
        WHERE C.STAFF_CODE = D.STAFF_CODE)
  GROUP BY TERM_SEM,TERM_YEAR,CLASS_CNAME,COURSE_NUM,COURSE_CNAME