ALTER TABLE LEARNING.STUDYPLAN_2 DROP REGISTER_NUMBER;
ALTER TABLE LEARNING.STUDYPLAN_2 DROP MAIN_FILE_PATH;
ALTER TABLE LEARNING.STUDYPLAN_2 DROP SUB_FILE_PATH;
ALTER TABLE LEARNING.STUDYPLAN_2 DROP MAIN_ORIGINAL_FILENAME;
ALTER TABLE LEARNING.STUDYPLAN_2 DROP SUB_ORIGINAL_FILENAME;
ALTER TABLE LEARNING.STUDYPLAN_2 DROP DELETED_AT;
ALTER TABLE LEARNING.STUDYPLAN_2 ADD COLUMN RGNO INT;
ALTER TABLE LEARNING.STUDYPLAN_2 ADD CONSTRAINT RGNO CHECK (RGNO IS NOT NULL);
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.STUDYPLAN_2');
ALTER TABLE LEARNING.STUDYPLAN_2 ADD COLUMN MAIN_FILE_ID INT;
ALTER TABLE LEARNING.STUDYPLAN_2 ADD CONSTRAINT MAIN_FILE_ID CHECK (MAIN_FILE_ID IS NOT NULL);
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.STUDYPLAN_2');
ALTER TABLE LEARNING.STUDYPLAN_2 ADD COLUMN SUB_FILE_ID INT;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.STUDYPLAN_2');

ALTER TABLE LEARNING.STUDYPLAN_2
ADD CONSTRAINT STUDYPLAN_2_UPLOAD_FILES__fk1
FOREIGN KEY (MAIN_FILE_ID) REFERENCES UPLOAD_FILES (ID) ON DELETE CASCADE;
ALTER TABLE LEARNING.STUDYPLAN_2
ADD CONSTRAINT STUDYPLAN_2_UPLOAD_FILES_ID_fk2
FOREIGN KEY (SUB_FILE_ID) REFERENCES UPLOAD_FILES (ID) ON DELETE CASCADE;