DROP INDEX LEARNING.STUDENT_COURSE_RECORD_COPY_IDX1;
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD RENAME COLUMN REGISTER_NUMBER TO RGNO;
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD ALTER RGNO SET DATA TYPE INT;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.STUDENT_COURSE_RECORD');
CREATE UNIQUE INDEX STUDENT_COURSE_RECORD_RGNO_uindex ON LEARNING.STUDENT_COURSE_RECORD (RGNO);
DROP INDEX LEARNING.STUDENT_COURSE_RECORD_RGNO_UINDEX;
CREATE INDEX STUDENT_COURSE_RECORD_RGNO_UINDEX ON LEARNING.STUDENT_COURSE_RECORD (RGNO);

ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT ADD COLUMN UPLOAD_FILE_ID INT;
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT ADD CONSTRAINT UPLOAD_FILE_ID CHECK (UPLOAD_FILE_ID IS NOT NULL);
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT');
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT DROP CONSTRAINT STUDENT_COURSE_RECORD_DOCUMENT_STUDENT_COURSE_RECORD_ID_FK;
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT
ADD CONSTRAINT STUDENT_COURSE_RECORD_DOCUMENT_STUDENT_COURSE_RECORD_ID_FK
FOREIGN KEY (CRID) REFERENCES STUDENT_COURSE_RECORD (ID);
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT DROP DOCUMENT;
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT DROP ORIGINAL_FILENAME;
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT DROP DELETED_AT;

ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT
ADD CONSTRAINT STUDENT_COURSE_RECORD_DOCUMENT_UPLOAD_FILES_ID_fk
FOREIGN KEY (UPLOAD_FILE_ID) REFERENCES UPLOAD_FILES (ID);
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT DROP CONSTRAINT STUDENT_COURSE_RECORD_DOCUMENT_STUDENT_COURSE_RECORD_ID_FK;
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT
ADD CONSTRAINT STUDENT_COURSE_RECORD_DOCUMENT_STUDENT_COURSE_RECORD_ID_FK
FOREIGN KEY (CRID) REFERENCES STUDENT_COURSE_RECORD (ID);

ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT DROP CONSTRAINT STUDENT_COURSE_RECORD_DOCUMENT_STUDENT_COURSE_RECORD_ID_FK;
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT
ADD CONSTRAINT STUDENT_COURSE_RECORD_DOCUMENT_STUDENT_COURSE_RECORD_ID_FK
FOREIGN KEY (CRID) REFERENCES STUDENT_COURSE_RECORD (ID);
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT DROP CONSTRAINT STUDENT_COURSE_RECORD_DOCUMENT_UPLOAD_FILES_ID_FK;
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT
ADD CONSTRAINT STUDENT_COURSE_RECORD_DOCUMENT_UPLOAD_FILES_ID_FK
FOREIGN KEY (UPLOAD_FILE_ID) REFERENCES UPLOAD_FILES (ID);


DROP VIEW LEARNING.STUDENT_COURSE_RECORD_COPY;



CREATE OR REPLACE VIEW STU_COURSE_RECORD_WITH_DETAILS AS (
  SELECT A.*,B.CNAME, C.STAFF_CNAME
  FROM STUDENT_COURSE_RECORD AS A
         INNER JOIN HS014357.STU_BASIS AS B ON A.RGNO = B.RGNO
         LEFT JOIN HS014357.STAFF C ON A.VERIFIER_STAFF_CODE = C.STAFF_CODE
)

RENAME TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT TO STUDENT_COURSE_RECORD_DOCUMENT_RELATION;

DROP TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT;

  CREATE TABLE STUDENT_COURSE_RECORD_DOCUMENT_RELATION
  (
  ID int NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
  CRID int NOT NULL,
  UPLOAD_FILE_ID int,
  CONSTRAINT STUDENT_COURSE_RECORD_DOCUMENT_RELATION_STUDENT_COURSE_RECORD_ID_FK FOREIGN KEY (CRID) REFERENCES STUDENT_COURSE_RECORD (ID),
  CONSTRAINT STUDENT_COURSE_RECORD_DOCUMENT_RELATION_UPLOAD_FILES_ID_FK FOREIGN KEY (UPLOAD_FILE_ID) REFERENCES UPLOAD_FILES (ID)
  );
  CREATE UNIQUE INDEX "STUDENT_COURSE_RECORD_DOCUMENT_RELATION_ID_pk" ON STUDENT_COURSE_RECORD_DOCUMENT_RELATION (ID)

CREATE VIEW STUDENT_COURSE_RECORD_DOCUMENT AS (
SELECT A.CRID,A.UPLOAD_FILE_ID,RGNO,FILE_PATH AS DOCUMENT,FILE_NAME AS ORIGINAL_FILENAME,TERM_YEAR,TERM_SEM,CREATED_AT,DELETED_AT
FROM STUDENT_COURSE_RECORD_DOCUMENT_RELATION AS A,UPLOAD_FILES AS B WHERE A.UPLOAD_FILE_ID = B.ID)

CREATE OR REPLACE VIEW STU_COURSE_RECORD_WITH_DETAILS AS (
  SELECT A.*,B.CNAME, C.STAFF_CNAME,B.REG_NO
  FROM STUDENT_COURSE_RECORD AS A
         INNER JOIN HS014357.STU_BASIS AS B ON A.RGNO = B.RGNO
         LEFT JOIN HS014357.STAFF C ON A.VERIFIER_STAFF_CODE = C.STAFF_CODE
)


