ALTER TABLE LEARNING.AUTOBIOGRAPHY DROP MAIN_ORIGINAL_FILENAME;
ALTER TABLE LEARNING.AUTOBIOGRAPHY DROP SUB_ORIGINAL_FILENAME;
ALTER TABLE LEARNING.AUTOBIOGRAPHY DROP REGISTER_NUMBER;
ALTER TABLE LEARNING.AUTOBIOGRAPHY DROP MAIN_FILE_PATH;
ALTER TABLE LEARNING.AUTOBIOGRAPHY DROP SUB_FILE_PATH;
ALTER TABLE LEARNING.AUTOBIOGRAPHY ADD COLUMN MAIN_FILE_ID INT;
ALTER TABLE LEARNING.AUTOBIOGRAPHY ADD COLUMN SUB_FILE_ID INT;
ALTER TABLE LEARNING.AUTOBIOGRAPHY ADD COLUMN RGNO INT;

ALTER TABLE LEARNING.AUTOBIOGRAPHY ALTER COLUMN MAIN_FILE_ID SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.AUTOBIOGRAPHY');
ALTER TABLE LEARNING.AUTOBIOGRAPHY ADD CONSTRAINT RGNO CHECK (MAIN_FILE_ID IS NOT NULL);
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.AUTOBIOGRAPHY');

ALTER TABLE LEARNING.AUTOBIOGRAPHY
ADD CONSTRAINT AUTOBIOGRAPHY_UPLOAD_FILES_ID_fk1
FOREIGN KEY (MAIN_FILE_ID) REFERENCES UPLOAD_FILES (ID) ON DELETE CASCADE;
ALTER TABLE LEARNING.AUTOBIOGRAPHY
ADD CONSTRAINT AUTOBIOGRAPHY_UPLOAD_FILES_ID_fk2
FOREIGN KEY (SUB_FILE_ID) REFERENCES UPLOAD_FILES (ID) ON DELETE CASCADE;

ALTER TABLE LEARNING.AUTOBIOGRAPHY DROP DELETED_AT;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.AUTOBIOGRAPHY');