RENAME TABLE ABSENT_RECORD             TO "__ABSENT_RECORD";   
RENAME TABLE COURSE_SUBMIT_SET         TO "__COURSE_SUBMIT_SET";   
RENAME TABLE COURSE_TEACHING           TO "__COURSE_TEACHING";   
RENAME TABLE GROUP_COUNSEL3            TO "__GROUP_COUNSEL3";   
RENAME TABLE STUDYPLAN                 TO "__STUDYPLAN";   
RENAME TABLE SUBMIT_COURSE             TO "__SUBMIT_COURSE";   
RENAME TABLE VCOURSE_SELECT            TO "__VCOURSE_SELECT";   
RENAME TABLE VCOURSE_TEACHING          TO "__VCOURSE_TEACHING";   
RENAME TABLE VSTAFF                    TO "__VSTAFF";   
RENAME TABLE VSTU_REG_DATA             TO "__VSTU_REG_DATA";   
RENAME TABLE ATTENDSUBMITTER           TO "__ATTENDSUBMITTER";   
RENAME TABLE CARDESUBMITTER            TO "__CARDESUBMITTER";   
RENAME TABLE COUNSELOR                 TO "__COUNSELOR";   
RENAME TABLE COURSE                    TO "__COURSE";   
RENAME TABLE COURSESUBMITTER           TO "__COURSESUBMITTER";   
RENAME TABLE MANAGER                   TO "__MANAGER";   
RENAME TABLE NCNU_UPLOAD_DATA          TO "__NCNU_UPLOAD_DATA";   
RENAME TABLE PERFORMANCESUBMITTER      TO "__PERFORMANCESUBMITTER";   
RENAME TABLE SCHOOL_CARDE_COVER        TO "__SCHOOL_CARDE_COVER";   
RENAME TABLE SCHOOL_CARDE_RECORD       TO "__SCHOOL_CARDE_RECORD";   
RENAME TABLE STUDENT_PERFORMANCE_COVER TO "__STUDENT_PERFORMANCE_COVER";   
RENAME TABLE SUBMIT_PERFORMANCE        TO "__SUBMIT_PERFORMANCE";   
RENAME TABLE SYSTEM_CONFIG             TO "__SYSTEM_CONFIG";   
RENAME TABLE TEACHER                   TO "__TEACHER";   
RENAME TABLE TUTOR                     TO "__TUTOR";   


