CREATE OR REPLACE VIEW  HS_VCOURSE_SELECT_RGNO AS (
  SELECT A.*
, B.RGNO
  FROM HS_VCOURSE_SELECT A
    INNER JOIN STU_RGNO_MAPPING B ON A.TERM_YEAR = B.TERM_YEAR AND A.TERM_SEM = B.TERM_SEM AND A.REG_NO = B.REG_NO
)