ALTER TABLE LEARNING.AUTOBIOGRAPHY ALTER COLUMN MAIN_ORIGINAL_FILENAME SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.AUTOBIOGRAPHY');

ALTER TABLE LEARNING.CADRE_RECORD ALTER COLUMN BIRTH DROP DEFAULT;
ALTER TABLE LEARNING.CADRE_RECORD ALTER COLUMN BIRTH SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.CADRE_RECORD');

ALTER TABLE LEARNING.CADRE_RECORD ALTER COLUMN BIRTH DROP DEFAULT;
ALTER TABLE LEARNING.CADRE_RECORD ALTER COLUMN BIRTH SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.CADRE_RECORD');
ALTER TABLE LEARNING.CADRE_RECORD ALTER COLUMN CREATED_AT SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.CADRE_RECORD');
ALTER TABLE LEARNING.CADRE_RECORD ALTER COLUMN SOURCE SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.CADRE_RECORD');
ALTER TABLE LEARNING.CADRE_RECORD ALTER COLUMN CHECK SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.CADRE_RECORD');
ALTER TABLE LEARNING.CADRE_RECORD ALTER COLUMN STATUS SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.CADRE_RECORD');
ALTER TABLE LEARNING.CADRE_RECORD ALTER COLUMN SUBMITTER SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.CADRE_RECORD');




ALTER TABLE LEARNING.COMPETITION_RECORD ALTER COLUMN BIRTH DROP DEFAULT;
ALTER TABLE LEARNING.COMPETITION_RECORD ALTER COLUMN BIRTH SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.CADRE_RECORD');
ALTER TABLE LEARNING.COMPETITION_RECORD ALTER COLUMN SOURCE SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.COMPETITION_RECORD');
ALTER TABLE LEARNING.COMPETITION_RECORD ALTER COLUMN SUBMITTER SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.COMPETITION_RECORD');
ALTER TABLE LEARNING.COMPETITION_RECORD ALTER COLUMN CHECK SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.COMPETITION_RECORD');
ALTER TABLE LEARNING.COMPETITION_RECORD ALTER COLUMN STATUS SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.COMPETITION_RECORD');


ALTER TABLE LEARNING.LICENSE_RECORD ALTER COLUMN BIRTH DROP DEFAULT;
ALTER TABLE LEARNING.LICENSE_RECORD ALTER COLUMN BIRTH SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.LICENSE_RECORD');
ALTER TABLE LEARNING.LICENSE_RECORD ALTER COLUMN SOURCE SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.LICENSE_RECORD');
ALTER TABLE LEARNING.LICENSE_RECORD ALTER COLUMN SUBMITTER SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.LICENSE_RECORD');
ALTER TABLE LEARNING.LICENSE_RECORD ALTER COLUMN CREATED_AT SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.LICENSE_RECORD');
ALTER TABLE LEARNING.LICENSE_RECORD ALTER COLUMN CHECK SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.LICENSE_RECORD');

ALTER TABLE LEARNING.OTHER_RECORD ALTER COLUMN BIRTH DROP DEFAULT;
ALTER TABLE LEARNING.OTHER_RECORD ALTER COLUMN BIRTH SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.OTHER_RECORD');



ALTER TABLE LEARNING.OTHER_RECORD ALTER COLUMN SOURCE SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.OTHER_RECORD');
ALTER TABLE LEARNING.OTHER_RECORD ALTER COLUMN SUBMITTER SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.OTHER_RECORD');
ALTER TABLE LEARNING.OTHER_RECORD ALTER COLUMN CREATED_AT SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.OTHER_RECORD');
ALTER TABLE LEARNING.OTHER_RECORD ALTER COLUMN TYPE SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.OTHER_RECORD');
ALTER TABLE LEARNING.OTHER_RECORD ALTER COLUMN CHECK SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.OTHER_RECORD');
ALTER TABLE LEARNING.OTHER_RECORD ALTER COLUMN STATUS SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.OTHER_RECORD');

ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT DROP CONSTRAINT STUDENT_COURSE_RECORD_DOCUMENT_STUDENT_COURSE_RECORD_ID_FK;
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT ALTER COLUMN CRID SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT');
ALTER TABLE LEARNING.STUDENT_COURSE_RECORD_DOCUMENT
ADD CONSTRAINT STUDENT_COURSE_RECORD_DOCUMENT_STUDENT_COURSE_RECORD_ID_FK
FOREIGN KEY (CRID) REFERENCES STUDENT_COURSE_RECORD (ID);


