drop table INDIVIDUAL_COUNSEL;
CREATE TABLE INDIVIDUAL_COUNSEL
(
  ID          INTEGER                             NOT NULL GENERATED ALWAYS AS IDENTITY,
  START_TIME  TIMESTAMP                           NOT NULL,
  END_TIME    TIMESTAMP                           NOT NULL,
  TITLE       VARCHAR(50)                         NOT NULL,
  LOCATION    VARCHAR(100),
  DESCRIPTION VARCHAR(300),
  COUNSELOR   VARCHAR(10)                         NOT NULL,
  SUBMITTER   VARCHAR(10),
  RGNO        INTEGER                             NOT NULL,
  CREATED_AT  TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
  FILE_ID     INTEGER,
  CONSTRAINT GROUP_COUNSEL_PK PRIMARY KEY (ID),
  CONSTRAINT INDIVIDUAL_COUNSEL_UPLOAD_FILES_ID_FK FOREIGN KEY (FILE_ID) REFERENCES
    "UPLOAD_FILES" ("ID") ON
    DELETE
    CASCADE
);

