ALTER TABLE LEARNING.COURSE_RECORD_UNLOCK_STATUS DROP REG_NO;
ALTER TABLE LEARNING.COURSE_RECORD_UNLOCK_STATUS ADD COLUMN RGNO INT;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.COURSE_RECORD_UNLOCK_STATUS');
ALTER TABLE LEARNING.COURSE_RECORD_UNLOCK_STATUS ADD COLUMN RGNO INT;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.COURSE_RECORD_UNLOCK_STATUS');
ALTER TABLE LEARNING.COURSE_RECORD_UNLOCK_STATUS ALTER COLUMN RGNO SET NOT NULL;
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.COURSE_RECORD_UNLOCK_STATUS');
ALTER TABLE LEARNING.COURSE_RECORD_UNLOCK_STATUS
 ADD CONSTRAINT "COURSE_RECORD_UNLOCK_STATUS_ACTIVE_YEAR_ACTIVE_SEM_RGNO_pk" UNIQUE (ACTIVE_YEAR, ACTIVE_SEM, RGNO);
CALL SYSPROC.ADMIN_CMD('REORG TABLE LEARNING.COURSE_RECORD_UNLOCK_STATUS');	