CREATE OR REPLACE VIEW HS_CUNIT_NAME          AS ( SELECT * FROM HS014357.CUNIT_NAME  );
CREATE OR REPLACE VIEW HS_DIVISION            AS ( SELECT * FROM HS014357.DIVISION    );
CREATE OR REPLACE VIEW HS_SUBJECT             AS ( SELECT * FROM HS014357.SUBJECT     );
CREATE OR REPLACE VIEW HS_CLASS_SBJ           AS ( SELECT * FROM HS014357.CLASS_SBJ   );
